### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by ttyfly** [TomatoServers/Task_for_test#1]
写得还可以，不过还存在几个问题：

1. 排序指的是将 data 中的数据进行排序，order 存储的是排序标准。比如按标题进行字典序排序，那么 order 就存 "title"。也就是你需要编写程序，对 data 中的内容进行排序，然后将排序标准存进 order。
2. 请将类似“作者：”、“时间：”这样的内容，用正则表达式滤去。
3. data 各条目里的 time 未按要求格式输出，请修改。

修改完后，可以直接在此 issue 下发表回复，我会再次查看。

**Comment by TomatoServers** [comment]
# -*- coding: utf-8 -*-
import datetime
import requests
import json
import re
from bs4 import BeautifulSoup

def time(date=datetime.date.today(),time=datetime.datetime.now()):
    new_time=str(time)
    new_date=str(date)
    time=new_date+'T'+new_time[11:19]
    return time

s=time()
findAuthor=re.compile(r'<span>作者：(.*?)</span>')
findTime=re.compile(r'<span>时间：<span data-type="updatetime">(.*?)</span></span>')
allDetail={
    'name':'安康要闻','order':'date','generated_at':s,'data':[]
}

def page(num):
    header={
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36'
    }
    url='http://www.ankang.gov.cn/Node-1466_'+num+'.html'
    data=requests.get(url=url,headers=header).text
    soup=BeautifulSoup(data,'lxml')
    title_list=soup.select('.putong > ul > li > a')
    for txt in title_list:
        title_name = txt.string
        detail_url = txt['href']
        detail_data = requests.get(url=detail_url, headers=header).text
        detail_soup = BeautifulSoup(detail_data, 'lxml')
        author =re.findall(findAuthor,str(detail_soup.find_all('span')[0]))[0]
        time = re.findall(findTime,str(detail_soup.find_all('span')[1]))[0].replace(' ','T')+':00'
        content = detail_soup.find('div', class_='wenz').text
        detail = {
            'title': title_name, 'author': author, 'time': time,'content': content.replace('\n', '').replace('\t', '')
        }
        allDetail['data'].append(detail)
    json_ = json.dumps(allDetail, indent=4, ensure_ascii=False)
    d = s.replace(':', '-')
    f = open('page_'+num+"安康要闻%s.json" %d, 'w',encoding='utf-8')
    f.write(json_)
    f.close()

while True:
    print('接下来将要爬取的内容是安康要闻，地址为http://www.ankang.gov.cn/Node-1466.html。\n请输入您想爬取的页码（1-1097）.按回车键结束')
    ans=input()
    try:
        if ans=='':
            break
        else:
            page(ans)
            print('爬取成功，已导出文件')

    except Exception:
        print('出现错误')``

改后的代码QAQ不过我感觉我实现这些目标的方式特别笨拙。

**Comment by ttyfly** [comment]
修改完的代码请直接推到仓库中qwq

关于时间格式转换，可以去看看 python datetime 的官方文档，会有你需要的东西的。

然后好像还是没有实现排序功能。就是通过控制台设置排序标准，按不同标准排序并输出。（不实现问题也不大，但是这是一项考察内容，最好还是写一下）

**Comment by TomatoServers** [comment]
学长，我想问几个问题QAQ。首先就是我将‘时间：’过滤后得到的时间数据已经符合datetime格式了，是否还需要datetime转化？
然后就是这个排序有没有具体的例子，我还是不能太理解QAQ。还有就是关于代码的问题，为什么我这个地方尝试抓取阅读量结果beautifulsoup解析出来的结果没有数字了？

**Comment by ttyfly** [comment]
（请将修改推到仓库里方便我 pull 下来测试 qwq）

如果已经符合格式了，那就不用转化了。但是你这里

```python
time = re.findall(findTime, str(detail_soup.find_all('span')[1]))[0].replace(' ','T') + ':00'
```

不是还是做了转化吗 qwq

排序的例子的话，比如你爬取之后，想按 date 顺序输出，那么就把 data 里的数据按 date 排一次序，然后令 order = "date"。如果想按标题的字典序（中文应该就是拼音顺序）排列，就把 data 里的数据按 title 排一次序，然后令 order = "title"。依此类推。然后可以通过一些方法（比如控制台输入），设置排序标准。至于如何按字典序排序，你可以去看看 python list 的 sort 函数。

然后阅读量，指的是浏览次数吗？感觉这个应该不难抓。我不知道你是怎么抓的，你可以把这部分代码也推到仓库里，我帮你看看。

**Comment by TomatoServers** [comment]
改完了，已经推到了库里

**Comment by ttyfly** [comment]
> 
> 
> 改完了，已经推到了库里

sort 部分已经符合要求（其实不用 pypinyin 也行，只是想让你们排个序，将字典序理解为拼音顺序是我的问题，咳咳咳）。

然后时间格式那里，我可能表述得不太清楚。我的意思是，这个时间格式还是和要求的格式不太一样，需要做一下转化。把之前那句代码加上就行了，所以已经可以算是完成了。

感谢您的参与。后续会公布参考代码和夏令营优秀营员名单，敬请关注。
